"""adding column data

Revision ID: 1d7c034f5200
Revises: c631a32c39a5
Create Date: 2026-07-04 14:14:38.241000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7c034f5200'
down_revision: Union[str, Sequence[str], None] = 'c631a32c39a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Update users set full_name = name where full_name is null."""
    # ### commands auto generated by Alembic - please adjust! #
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
