"""add details to full_name

Revision ID: 269803d9344c
Revises: da728ee8f1a7
Create Date: 2026-07-06 21:00:38.168902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269803d9344c'
down_revision: Union[str, Sequence[str], None] = 'da728ee8f1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE day_8_practice.customers SET full_name = name WHERE full_name IS NULL")
    )
  
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
