"""addint ticket_messages

Revision ID: 2d4a0835994f
Revises: acbe0e4b9bfd
Create Date: 2026-07-06 21:15:55.117315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4a0835994f'
down_revision: Union[str, Sequence[str], None] = 'acbe0e4b9bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['day_8_practice.tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='day_8_practice'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_messages', schema='day_8_practice')
    # ### end Alembic commands ###
