"""contracting

Revision ID: acbe0e4b9bfd
Revises: 269803d9344c
Create Date: 2026-07-06 21:13:02.523956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbe0e4b9bfd'
down_revision: Union[str, Sequence[str], None] = '269803d9344c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='day_8_practice')
    op.drop_constraint(op.f('customers_name_key'), 'customers', schema='day_8_practice', type_='unique')
    op.drop_column('customers', 'name', schema='day_8_practice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False), schema='day_8_practice')
    op.create_unique_constraint(op.f('customers_name_key'), 'customers', ['name'], schema='day_8_practice', postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='day_8_practice')
    # ### end Alembic commands ###
