"""add full_name

Revision ID: da728ee8f1a7
Revises: 7ecbed108640
Create Date: 2026-07-06 20:59:51.997321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da728ee8f1a7'
down_revision: Union[str, Sequence[str], None] = '7ecbed108640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('full_name', sa.String(), nullable=True), schema='day_8_practice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'full_name', schema='day_8_practice')
    # ### end Alembic commands ###
