"""v9

Revision ID: 2c099b5cff30
Revises: fe722fb0983d
Create Date: 2026-07-27 15:41:04.551498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c099b5cff30'
down_revision: Union[str, Sequence[str], None] = 'fe722fb0983d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='prep_day10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='prep_day10')
    # ### end Alembic commands ###
