"""v2

Revision ID: 3a25466f05d6
Revises: 3c4cb85e0c9c
Create Date: 2026-07-18 14:54:30.206570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a25466f05d6'
down_revision: Union[str, Sequence[str], None] = '3c4cb85e0c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'device_info',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='prep_day10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'device_info',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='prep_day10')
    # ### end Alembic commands ###
