"""v1

Revision ID: 3c4cb85e0c9c
Revises: 
Create Date: 2026-07-18 14:04:54.987877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4cb85e0c9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='prep_day10'
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['prep_day10.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prep_day10'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_token', sa.LargeBinary(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['prep_day10.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prep_day10'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens', schema='prep_day10')
    op.drop_table('artifacts', schema='prep_day10')
    op.drop_table('users', schema='prep_day10')
    # ### end Alembic commands ###
