"""v3

Revision ID: 56cf7c34b864
Revises: 579e0cd96949
Create Date: 2026-07-24 17:20:48.394242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56cf7c34b864'
down_revision: Union[str, Sequence[str], None] = '579e0cd96949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expire', sa.DateTime(), nullable=False), schema='prep_day10')
    op.add_column('refresh_tokens', sa.Column('device', sa.String(), nullable=True), schema='prep_day10')
    op.drop_column('refresh_tokens', 'expires_at', schema='prep_day10')
    op.drop_column('refresh_tokens', 'device_info', schema='prep_day10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_info', sa.VARCHAR(), autoincrement=False, nullable=True), schema='prep_day10')
    op.add_column('refresh_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='prep_day10')
    op.drop_column('refresh_tokens', 'device', schema='prep_day10')
    op.drop_column('refresh_tokens', 'expire', schema='prep_day10')
    # ### end Alembic commands ###
