"""v3

Revision ID: 579e0cd96949
Revises: f57ce1f64846
Create Date: 2026-07-24 17:19:26.124598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579e0cd96949'
down_revision: Union[str, Sequence[str], None] = 'f57ce1f64846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('ip', sa.String(), nullable=False), schema='prep_day10')
    op.drop_column('refresh_tokens', 'ip_address', schema='prep_day10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False), schema='prep_day10')
    op.drop_column('refresh_tokens', 'ip', schema='prep_day10')
    # ### end Alembic commands ###
