"""empty message

Revision ID: 9c9bb778c859
Revises: 56cf7c34b864
Create Date: 2026-07-27 14:29:47.991529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9bb778c859'
down_revision: Union[str, Sequence[str], None] = '56cf7c34b864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='prep_day10'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='prep_day10'
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['prep_day10.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['prep_day10.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='prep_day10'
    )
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True), schema='prep_day10')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='prep_day10', referent_schema='prep_day10')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='prep_day10', type_='foreignkey')
    op.drop_column('users', 'role_id', schema='prep_day10')
    op.drop_table('role_permissions', schema='prep_day10')
    op.drop_table('roles', schema='prep_day10')
    op.drop_table('permissions', schema='prep_day10')
    # ### end Alembic commands ###
