"""v6

Revision ID: fe722fb0983d
Revises: 9c9bb778c859
Create Date: 2026-07-27 14:42:33.269063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe722fb0983d'
down_revision: Union[str, Sequence[str], None] = '9c9bb778c859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn=op.get_bind()
    conn.execute(sa.text("update prep_day10.roles set name='admin' where id=2"))
    conn.execute(sa.text("update prep_day10.roles set name='user' where id=1"))
    conn.execute(sa.text("update prep_day10.users set role_id=1 where role_id is null"))

        # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
